### ISSUE TITLE
SpinApp deployment fails due to missing replicas when enableAutoscaling: true

### ISSUE THREAD

**Issue by macolso** [spinframework/spin-operator#18]
Deploying a SpinApp that should be scaled via HPA/KEDA (`enableAutoscaling: true`) currently fails due to missing value for `replicas`.

To repro, try to deploy `config/samples/hpa.yaml`:

```bash
kubectl apply -f config/samples/hpa.yaml

horizontalpodautoscaler.autoscaling/spinapp-autoscaler created
The SpinApp "hpa-spinapp" is invalid: spec.replicas: Required value
```
Although `kubectl explain spinapp.spec.enableAutoscaling` mentions this

> EnableAutoscaling indicates whether the app is allowed to autoscale. If true then the operator leaves the replica count of the underlying deployment to be managed by an external autoscaler (HPA/KEDA). Replicas cannot be defined if this is enabled. By default EnableAutoscaling is false.

Deployment and auto-scaling (in the case of KEDA) https://github.com/spinkube/spin-operator/pull/4 works if I specify both as shown here:

```yaml
apiVersion: core.spinoperator.dev/v1
kind: SpinApp
metadata:
  name: keda-spinapp
spec:
  image: "ttl.sh/cpu-load-gen:1h"
  executor: containerd-shim-spin
  enableAutoscaling: true
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 400Mi
```
